import { ClaimVerificationSchema, FactPackSchema, SourceEvidenceMapSchema, type FactPack } from "@upcraft/contracts";
import { eq } from "drizzle-orm";
import { getDb, sourceClaims } from "@upcraft/db";
import { generateStructuredText, reviewWithRoute } from "@upcraft/providers";
import { saveArtifact, requireContent } from "../../artifacts/store.ts";
import { sha } from "../../artifacts/hashing.ts";
import { withFallback } from "../../fallback.ts";
import { recordUsage } from "../../usage.ts";
import { planClaimSetReplacement, runClaimVerificationPolicyLoop, type CorrectionPrompt } from "../../verification.ts";
import { contextManifest, projectFactVerificationContext, sourceEvidenceSegments } from "../../context.ts";
import { factPackJsonSchema } from "../../prompts/fact-pack.ts";
import { getRun } from "../../runs.ts";
import type { StageContext } from "../context.ts";

type Json = Record<string, unknown>;

const sourceContextOf = (map: ReturnType<typeof SourceEvidenceMapSchema.parse>) =>
  map.sources.map((source) => `SOURCE ${source.sourceId} HASH ${source.sourceHash}\n${source.segments.map((segment) => `SEGMENT ${segment.id} [${segment.startOffset}:${segment.endOffset}]\n${segment.text}`).join("\n")}`).join("\n\n");

const repairPrompt = (params: { correction: CorrectionPrompt; previousPack: FactPack; sourceContext: string; snapshotProjection: string }) =>
  `A separate verifier rejected these claim ids: ${params.correction.rejectedIds.join(", ")}.\nVerifier rationale: ${params.correction.rationale}\nCorrection contract: ${params.correction.contract}\nPreserve every already-accepted claim id and its text exactly; rewrite only the rejected claims so each is supported by its cited segment. ${params.snapshotProjection}Return JSON with schemaVersion "fact-pack/v2", claims [{id, text, evidence {sourceId, sourceHash, segmentIds, locator}, critical}], and caveats [{text, evidence?}]. Every claim must cite one or more supplied segment IDs. Do not quote or reproduce source text in the output.\n\nPrevious fact pack (accepted claims are locked):\n${JSON.stringify(params.previousPack)}\n\n${params.sourceContext}`;

/**
 * §3 M2 independent claim verification over the locked fact pack.
 *
 * Repair-first, drop-on-exhaustion: a rejected claim is re-generated by the
 * planning route with a targeted correction prompt (bounded, max 3 attempts). A
 * critical claim still unsupported at exhaustion throws the terminal
 * `VERIFIER_REJECTION_EXHAUSTED`; a non-critical claim is dropped and recorded as
 * an omission on `verified-fact-pack/v1`. The accepted/omitted set replaces the
 * run's `source_claims` rows in one transaction.
 */
export const runFactVerification = async (ctx: StageContext): Promise<unknown> => {
  const { runId } = ctx;
  const factPack = requireContent(await ctx.getArtifact(runId, "fact-pack"), "fact-pack");
  const evidenceMap = SourceEvidenceMapSchema.parse(requireContent(await ctx.getArtifact(runId, "source-evidence-map"), "source-evidence-map"));
  const parsedFactPack = FactPackSchema.parse(factPack);
  const route = ctx.route("fact-verification")!;
  const planningRoute = ctx.route("research");
  if (!planningRoute) throw new Error("Fact-pack repair requires the research route");
  const run = await getRun(runId);
  if (!run) throw new Error("Run not found");
  const snapshotProjection = `Learner level: ${run.snapshot.learningLevel}\nAudience: ${run.snapshot.audienceCategory}\nLanguage: ${run.snapshot.language}\n`;
  const sourceContext = sourceContextOf(evidenceMap);

  const verify = async (pack: FactPack, _attempt: number) => {
    const startedAt = Date.now();
    const windowed = projectFactVerificationContext(pack, evidenceMap);
    const prompt = `Independently verify every claim against only its supplied source segments. Return schemaVersion "claim-verification/v2", one evidence item per claim with claimId, sourceId, segmentIds, supported, rationale, and notes. Do not add facts, use uncited sources, or reproduce source text.\n${JSON.stringify(windowed)}`;
    const verificationRun = await withFallback(route, (attemptRoute) => reviewWithRoute(attemptRoute, prompt), async (failedRoute, error) => {
      await recordUsage(runId, "fact-verification", failedRoute.provider, failedRoute.model, startedAt, { model: failedRoute.model }, "fact-verification/v2", { projection: "claim-local-evidence-windowed/v1" }, "failed", error.code);
    });
    await recordUsage(runId, "fact-verification", verificationRun.route.provider, verificationRun.route.model, startedAt, verificationRun.value.usage, "fact-verification/v2", contextManifest(
      "claim-local-evidence-windowed/v1",
      [{ role: "fact-verification-context", hash: sha(windowed), chars: JSON.stringify(windowed).length, itemCount: windowed.evidenceSegments.length }],
      { citedSegments: windowed.manifest.citedSegments, neighborSegments: windowed.manifest.neighborSegments, omittedNeighborSegments: windowed.manifest.omittedNeighborSegments },
    ));
    return ClaimVerificationSchema.parse(verificationRun.value.value);
  };

  const generate = async (correction: CorrectionPrompt | null): Promise<FactPack> => {
    if (!correction) return parsedFactPack;
    const startedAt = Date.now();
    const prompt = repairPrompt({ correction, previousPack: parsedFactPack, sourceContext, snapshotProjection });
    const generated = await withFallback(planningRoute, (attemptRoute) => generateStructuredText<Json>(attemptRoute, { schemaName: "fact_pack", jsonSchema: factPackJsonSchema, prompt }), async (failedRoute, error) => {
      await recordUsage(runId, "fact-verification", failedRoute.provider, failedRoute.model, startedAt, { model: failedRoute.model }, "fact-pack-repair/v1", { projection: "source-full-segmented/v1" }, "failed", error.code);
    });
    await recordUsage(runId, "fact-verification", generated.route.provider, generated.route.model, startedAt, generated.value.usage, "fact-pack-repair/v1", contextManifest("source-full-segmented/v1", [{ role: "source-evidence-map", hash: sha(evidenceMap), chars: sourceContext.length, itemCount: evidenceMap.sources.reduce((sum, source) => sum + source.segments.length, 0) }]));
    const pack = FactPackSchema.parse(generated.value.value);
    for (const claim of pack.claims) sourceEvidenceSegments(evidenceMap, [claim.evidence]);
    for (const caveat of pack.caveats) if (caveat.evidence) sourceEvidenceSegments(evidenceMap, [caveat.evidence]);
    return pack;
  };

  const loop = await runClaimVerificationPolicyLoop({ factPack: parsedFactPack, generate, verify, verifierModel: route.model });
  const verifiedFactPack = loop.verifiedFactPack;

  const replacement = planClaimSetReplacement(runId, verifiedFactPack, route.model);
  await getDb().transaction(async (tx) => {
    await tx.delete(sourceClaims).where(eq(sourceClaims.runId, runId));
    if (replacement.insert.length) await tx.insert(sourceClaims).values(replacement.insert);
  });

  return saveArtifact({ runId, stage: "fact-verification", role: "verified-fact-pack", schemaVersion: verifiedFactPack.schemaVersion, inputHash: sha(factPack), content: verifiedFactPack });
};
